### ISSUE TITLE
Form Does Not Save on Production Site...Raises Error

### ISSUE THREAD

**Issue by Microflow** [Microflow/citybuilder#108]
Need to look at the old conversations about when the form didn't work last time.

An ascii cinema to help junior developers understand how to trace errors would be good.

**Comment by Microflow** [comment]
## What Commands Should Programmers Use to Diagnose?

/etc/init.d/nginx status

**Comment by Microflow** [comment]
jake@fk:~/citybuilder/var/log$ ls -a

**Comment by Microflow** [comment]
cat erlang.log.1

**Comment by Microflow** [comment]
tail -30 erlang.log.3

**Comment by Microflow** [comment]
Example: 302 is a redirect:

14:20:18.251 request_id=19kt72hf4p4ftees13e07a0pu5fr4kok [info] Sent 302 in 1ms
14:20:18.342 request_id=066qgkjsns3ci315iu790d4p0lebnb7r [info] GET /users/signin

**Comment by Microflow** [comment]
@denispeplin 
I'm not sure how I can see where the form is raising an error. Nothing is showing in the erlang logs.

I think the validation is coming from Phoenix JS, but don't know where.

**Comment by denispeplin** [comment]
Fixed by #110

**Comment by Microflow** [comment]
Good news. Will check soon... the form was saving ok last night.
