### ISSUE TITLE
India URL not working in staging (works ok in development)

### ISSUE THREAD

**Issue by Microflow** [Microflow/citybuilder#123]
http://citybuilder.microflow.io/india

*** System restart required ***
Last login: Sun Oct  1 23:40:35 2017 from 104.199.227.129

## Error logs

00:36:16.985 [info] Running Citybuilder.Web.Endpoint with Cowboy using http://:::4001
Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(citybuilder@127.0.0.1)1> 
===== Mon Oct  2 00:43:03 UTC 2017
00:43:03.513 request_id=7m4jjfdajuh7u7j131vo0ubc7hao2lm0 [info] GET /india
00:43:03.521 request_id=7m4jjfdajuh7u7j131vo0ubc7hao2lm0 [info] Sent 404 in 8ms
00:45:49.012 request_id=9n02d2rbdbfnacljn6co387uire377ch [info] GET /
00:45:49.019 request_id=9n02d2rbdbfnacljn6co387uire377ch [info] Sent 200 in 7ms

**Comment by denispeplin** [comment]
Not working because there is no country seeded. Does it work now?

**Comment by Microflow** [comment]
Yes, it works.

Closed.
