### ISSUE TITLE
502 Bad Gateway (After Entering User Form Information)

### ISSUE THREAD

**Issue by Microflow** [Microflow/citybuilder#58]
**When user submits a form, NGINX returns 502 bad gateway.**

*

## Misc Notes

https://askubuntu.com/questions/879096/nginx-502-bad-gateway

The 502 Bad Gateway error means server is not getting proper response from another server.

**Comment by Microflow** [comment]
## Misc 502 Bad Gateway Links

https://www.scalescale.com/tips/nginx/502-bad-gateway-error-using-nginx/

https://www.digitalocean.com/community/questions/502-bad-gateway-nginx-2

https://www.theguardian.com/technology/askjack/2013/aug/01/502-bad-gateway-error

https://www.digitalocean.com/community/questions/nginx-502-bad-gateway-s3-upload

**Comment by Microflow** [comment]
Added this:

fastcgi_buffers 8 16k;
fastcgi_buffer_size 32k;
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;

From:

https://stackoverflow.com/questions/39185268/502-bad-gateway

**Comment by denispeplin** [comment]
These fastcgi configs are not relevant to our problem.
App fails very fast, raising 500 error. So no point touching nginx.

**Comment by Microflow** [comment]
OK, I will ignore the fastcgi configs.

Form now submits and redirects to display page, but pictures do not show on production site.
