### ISSUE TITLE
Project Submit Form Needs a Wizard

### ISSUE THREAD

**Issue by Microflow** [Microflow/citybuilder#64]
Please group all example codepens, or sites with Wizards you like, here.

**Comment by Siriki-Saikiran** [comment]
https://codepen.io/lukezak/details/LVJRva

**Comment by Siriki-Saikiran** [comment]
https://codepen.io/atakan/full/gqbIz/

**Comment by Siriki-Saikiran** [comment]
https://www.creative-tim.com/search?utf8=%E2%9C%93&q=form+wizard&button=
